version: '3.8'

services:
  api:
    image: python:3.9
    working_dir: /code
    container_name: pop-api
    ports:
      - "8003:8000"
    environment:
      - PYTHONPATH=/code
      - TZ=${TZ:-UTC}  # Use host TZ environment variable, fallback to UTC
    volumes:
      - ./api:/code/api
      - ./.env:/code/.env
      - ./requirements.txt:/code/requirements.txt
      - ./tests:/code/tests
      - ./static:/code/static
      - ./pytest.ini:/code/pytest.ini
      - ./logs:/code/logs
      - /etc/localtime:/etc/localtime:ro  # Mount host timezone info (Linux/macOS)
      - /etc/timezone:/etc/timezone:ro    # Mount host timezone name (Linux)
    networks:
      - backend
    # Add a step to install dependencies before starting the server
    entrypoint: >
      /bin/bash -c
      "pip install --no-cache-dir --upgrade -r /code/requirements.txt &&
      uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload --workers 5"

networks:
  backend:
    driver: bridge
