version: "3"

services:
  jupyterhub:
   build:
     context: .
     dockerfile: Dockerfile
     args:
       JUPYTERHUB_VERSION: latest
   restart: always
   networks:
     - jupyterhub-network
   volumes:
     - "./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
     - "/var/run/docker.sock:/var/run/docker.sock:rw"
     - "jupyterhub:/data"
   ports:
     - 8002:${JUPYTERHUB_PROXY_PORT}
   environment:
     - JUPYTERHUB_PROXY_PORT
     - JUPYTERHUB_PORT
     - JUPYTERHUB_ADMIN
     - DOCKER_NETWORK_NAME
     - DOCKER_NOTEBOOK_IMAGE
     - DOCKER_NOTEBOOK_DIR
     # for MLFlow connection:
#     - AWS_ACCESS_KEY_ID
#     - AWS_SECRET_ACCESS_KEY
#     - MLFLOW_TRACKING_URI
#     - MLFLOW_S3_ENDPOINT_URL
#     - AWS_BUCKET_NAME
#     - MLFLOW_DEFAULT_PASSWORD
#     - MLFLOW_ADMIN_USERNAME
#     - MLFLOW_ADMIN_PASSWORD
     # keycloak
     - JUPYTERHUB_KEYCLOAK_CLIENT_ID
     - JUPYTERHUB_KEYCLOAK_CLIENT_SECRET
     - JUPYTERHUB_AUTHORIZE_URL
     - JUPYTERHUB_TOKEN_URL
     - JUPYTERHUB_OAUTH_CALLBACK_URL
     - JUPYTERHUB_USERDATA_URL
     - JUPYTERHUB_LOGOUT_REDIRECT_URL
     - CKAN_API_URL
     - WORKSPACE_API_URL
     - REFRESH_EVERY_SECONDS
     - NDP_EXT_VERSION
volumes:
  jupyterhub:

networks:
  jupyterhub-network:
    name: jupyterhub-network

